### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Meekohi** [uploadcare/uploadcare-bower#3]
```
[16:07:36] gulp-notify: [Compile Error] ./bower_components/Uploadcare/uploadcare.js: 'with' in strict mode (4079:116) while parsing file: ./bower_components/Uploadcare/uploadcare.js
```

**Comment by dmitry-mukhin** [comment]
@homm ?

**Comment by homm** [comment]
@Meekohi Could you explain more precisely, when you are seeing this message? By the way, the "with" statement is indeed used in the widget. But not in "strict mode".

**Comment by Meekohi** [comment]
This must be an error on my end then. I am seeing this when using gulp to compile a bunch of JS down into a single file (the majority of which is in strict mode), so I'm guessing someone else's "strict mode" is getting included. I'll take a closer look.
